### ISSUE TITLE
「体育の日」の改称（「スポーツの日」）への対応

### ISSUE THREAD

**Issue by 243f6a8885a308d313198a2e037** [holidays-jp/api#1]
> 「スポーツの日」について
> 令和２年（2020年）以降、「体育の日」は「スポーツの日」になります。

https://www8.cao.go.jp/chosei/shukujitsu/gaiyou.html

**Comment by matsuoshi** [comment]
issue ありがとうございます、「スポーツの日」に名称変更しました
