### ISSUE TITLE
`/api/v1/date` の挙動が破壊的に変更されている？

### ISSUE THREAD

**Issue by kissge** [holidays-jp/api#3]
いつも便利に利用させていただいております。ありがとうございます。

APIドキュメントに以下の記述があり、従来実際 `/api/v1/date` は**3年分のデータ**を返していたのですが、現在は**2019年から2029年**のデータに変わったようです。

> 去年・今年・来年のデータが取得可能です。

変更のあったコミット https://github.com/holidays-jp/api/commit/ee77eb0cb09f1f3d36932717591c37de7d6f6593

挙動を戻すか、あるいはドキュメントを変えるか、どちらかが親切かもしれません。

**Comment by hnx8** [comment]
同じく便利に利用させていただいております。助かっております。
またこのデータの変更の際に
2019年（令和元年）の「体育の日」が「スポーツの日」に書き変わってしまっているように思われます。
（2020年以降は「スポーツの日」となりましたが、2019年に限っては名称変更前なので「体育の日」が正）

**Comment by matsuoshi** [comment]
コメントありがとうございます、確認しますね

**Comment by matsuoshi** [comment]
@kissge さん、ご連絡ありがとうございます
たしかに破壊的変更といえますので、以前までのように去年・今年・来年のデータとなるよう、挙動を戻しました。

@hnx8 さん、ご連絡ありがとうございます、
こちらも #4 のほうで変更対応しました

**Comment by kissge** [comment]
ありがとうございます！🤗
