### ISSUE TITLE
googleカレンダーの日本の祝日におけるその他の休日も祝日としてjsonおよびcsvファイル内に登録されている

### ISSUE THREAD

**Issue by shino3418** [holidays-jp/api#7]
いつも利用させていただいております。

2024年9月から
[こちら](https://github.com/holidays-jp/api/tree/master/docs/v1)の配下の各jsonやcsvファイル内に
googleカレンダーの日本の祝日におけるその他の休日も祝日として登録されるようになったようです。

もし可能でしたら該当ファイルからその他の休日は除外していただくか、
難しい場合は除外済みの新たなjson,csvを作成していただくことはできますでしょうか。

ご検討いただけますと幸いです。

**Comment by niiharamegumu** [comment]
同様の事象でISSUEを作成しようとした所、既存でございましたのでこちらに補足記事を添付させていただきます。
[参考記事](https://support.gluegent.com/hc/ja/articles/4501698723870--%E9%9A%9C%E5%AE%B3-%E6%9C%AC%E6%9D%A5%E7%A5%9D%E6%97%A5%E3%81%A7%E3%81%AA%E3%81%84%E6%97%A5%E3%81%8C%E4%BC%91%E6%97%A5%E3%81%A8%E3%81%97%E3%81%A6%E8%A1%A8%E7%A4%BA%E3%81%95%E3%82%8C%E3%82%8B%E4%BA%8B%E8%B1%A1%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6)

**Comment by hmatsuo-ic** [comment]
ご迷惑おかけしました、取り急ぎ以前のデータに戻しましたのでご確認ください

**Comment by matsuoshi** [comment]
ご迷惑おかけしました、取り急ぎ以前のデータに戻しましたのでご確認ください。

**Comment by shino3418** [comment]
@matsuoshi 
ありがとうございます！
以前のデータに戻っていることを確認しました！
